markdown: redcarpet
paginate: 50
permalink: /:categories/:title
highlighter: pygments
redcarpet:
  extensions:
    - strikethrough
    - fenced_code_blocks
exclude: ['Gemfile','Gemfile.lock','serve.sh']
