paginate: 50
permalink: /:categories/:title/
exclude: ['serve.sh']
# Same as GFM, but without the tagfilter extension to allow <script>
# https://github.com/github/pages-gem/blob/e23e19e6faab746887ec440e7501585e89ef849c/lib/github-pages/configuration.rb#L135
markdown: CommonMarkGhPages
commonmark:
  extensions: ["table", "strikethrough", "autolink"]
  options: ["unsafe", "footnotes"]
