name: pages build check

on:
  push:
    branches-ignore: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Setup WireIt caching
        uses: google/wireit@setup-github-actions-caching/v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
